site_name: musings
nav:
    - Introduction: 'index.md'
    - 'about.md'
theme:
    name: forestry
    custom_dir: my_theme_customizations/
    static_templates:
        - sitemap.html
    include_sidebar: false
