---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: docs/f1/mclaren
  label: mclaren
- type: directory
  path: docs/f1
  label: f1
  create: all
  match: "**/*"
- type: directory
  path: docs
  label: docs
  create: all
  match: "**/*"
- type: document
  path: docs/thoughts.md
  label: thoughts
- type: document
  path: docs/index.md
  label: index
- type: document
  path: docs/about.md
  label: about
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
